<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductDetail;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            //Racquet
            [
                'productName' => 'YONEX ASTROX 88 D PRO',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Racquet',
                'productBrand' => 'YONEX',
                'description' => "A stiff racquet made from HM Graphite, CFR, and Tungsten,with 2G-Namd FLEX FORCE and Ultra PE Fiber for enhanced flexibility and power. Features a NEW Built-in T-Joint for improved stability. Measures 680mm (10mm longer for extra reach). Weighs 4U (Avg. 83g), with a recommended tension of 20-28 lbs. Available in Black and Silver. Made in Japan.",
                'stock' => 50,
                'imgPath' => 'Products/Racquet/YONEX ASTROX 88 D PRO.png',
                'equipPrice' => 839.90,
            ],
            [
                'productName' => 'YONEX ASTROX 100ZZ',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Racquet',
                'productBrand' => 'YONEX',
                'description' => "An extra stiff racquet constructed with HM Graphite, Namd, Tungsten, Black Micro Core, and Nanometric for maximum power and control. The shaft is made of HM Graphite and Namd for enhanced repulsion. Features a NEW Built-in T-Joint for improved stability. Measures 680mm (10mm longer for extended reach). Weighs 4U (Avg. 83g), with a recommended tension of 20-28 lbs. Available in Kurenai and Dark Navy. Made in Japan.",
                'stock' => 40,
                'imgPath' => 'Products/Racquet/YONEX ASTROX 100ZZ.png',
                'equipPrice' => 899.90,
            ],
            [
                'productName' => 'LI- NING AXFORCE 100 QILIN BLACK GOLD',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Racquet',
                'productBrand' => 'LI- NING',
                'description' => "A stiff racquet made from Extra High Elastic Carbon Fiber with a STD High-Modulus Carbon Fiber shaft for enhanced durability and power. Features a NEW Built-in T-Joint for improved stability. Measures 680mm (10mm longer for extended reach). Weighs 4U G5, with a recommended tension of 23-31 lbs. Available in Black and Gold. Made in China.",
                'stock' => 60,
                'imgPath' => 'Products/Racquet/LI- NING AXFORCE 100 QILIN BLACK GOLD.png',
                'equipPrice' => 980.00,
            ],
            [
                'productName' => 'LI- NING BLADE X 700 BLUE',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Racquet',
                'productBrand' => 'LI- NING',
                'description' => "A stiff racquet made from carbon fiber, featuring a hard flexible shaft for balanced power and control. Equipped with a Built-in T-Joint for enhanced stability. Measures 675mm in length. Weighs 3U G5, with a recommended tension of 23-31 lbs. Available in Blue. Made in China.",
                'stock' => 30,
                'imgPath' => 'Products/Racquet/LI- NING BLADE X 700 BLUE.png',
                'equipPrice' => 729.00,
            ],
            [
                'productName' => 'VICTOR IRON MAN METALLIC MA-IRONMAN',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Racquet',
                'productBrand' => 'VICTOR',
                'description' => "A stiff racquet constructed with High Resilience Modulus Graphite, Nano Resin, Metallic Carbon Fiber, and Hard Cored Technology for enhanced durability and responsiveness. The shaft is made of High Resilience Modulus Graphite and Nano Resin for improved repulsion. Features a Built-in T-Joint for better stability. Measures 675mm in length. Weighs 4U G5, with a recommended tension of 22-28 lbs. Available in Red. Made in Taiwan.",
                'stock' => 45,
                'imgPath' => 'Products/Racquet/VICTOR IRON MAN METALLIC GB D Badminton Racket MA.png',
                'equipPrice' => 1050.00,
            ],
            [
                'productName' => 'VICTOR MJOLNIR METALLIC MA-MJOLNIR',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Racquet',
                'productBrand' => 'VICTOR',
                'description' => "A stiff racquet made from High Resilience Modulus Graphite, Metallic Carbon Fiber, and Hard Cored Technology for enhanced power and durability. The shaft features High Resilience Modulus Graphite with a 6.8mm diameter for improved flexibility and control. Equipped with a Built-in T-Joint for better stability. Measures 675mm in length. Weighs 4U G6, with a recommended tension of 22-30 lbs. Available in Blue. Made in Taiwan.",
                'stock' => 65,
                'imgPath' => 'Products/Racquet/VICTOR MJOLNIR METALLIC Limited Racket Badminton Racket MA-MJOLNIR.png',
                'equipPrice' => 950.00,
            ],
            [
                'productName' => 'Cadence Edgeless 16 Pickleball Paddle',
                'sportCategory' => 'Pickleball',
                'productCategory' => 'Racquet',
                'productBrand' => 'WILSON',
                'description' => "The Cadence Edgeless 16 Pickleball Paddle is engineered for precision, power, and control. Featuring an edgeless design, it provides a larger sweet spot for enhanced shot consistency. The 16mm polymer core delivers exceptional touch and reduced vibrations, making it ideal for both aggressive and finesse players. Its carbon fiber face ensures durability and maximum spin potential. Designed for competitive play, the Cadence Edgeless 16 offers a lightweight yet powerful feel, helping you dominate the court with every shot. Elevate your game with this high-performance paddle!",
                'stock' => 35,
                'imgPath' => 'Products/Racquet/Cadence Edgeless 16 Pickleball Paddle.png',
                'equipPrice' => 703.00,
            ],

            [
                'productName' => 'Fierce Team 13 Chicago Pickleball Paddle',
                'sportCategory' => 'Pickleball',
                'productCategory' => 'Racquet',
                'productBrand' => 'WILSON',
                'description' => "The Fierce Team 13 Chicago Pickleball Paddle is built for players who demand precision and power. Featuring a 13mm polypropylene core, it offers a responsive feel with excellent control. The carbon fiber surface enhances durability and spin potential, making it ideal for competitive play. Its lightweight yet sturdy design allows for quick reactions at the net while maintaining powerful shots from the baseline. Inspired by the energy of Chicago, this paddle delivers performance and style, helping you take your game to the next level.",
                'stock' => 65,
                'imgPath' => 'Products/Racquet/Fierce Team 13 Chicago Pickleball Paddle.png',
                'equipPrice' => 310.70,
            ],
            [
                'productName' => 'Fierce Team 13 California Pickleball Paddle',
                'sportCategory' => 'Pickleball',
                'productCategory' => 'Racquet',
                'productBrand' => 'WILSON',
                'description' => "The Fierce Team 13 California Pickleball Paddle combines power, precision, and style for high-performance play. Designed with a 13mm polypropylene core, it provides a perfect balance of control and responsiveness. The carbon fiber surface enhances spin and durability, ensuring consistent performance on the court. Lightweight yet powerful, this paddle allows for quick reflexes at the net and solid baseline shots. Inspired by the energy and spirit of California, it’s perfect for players looking to elevate their game with confidence and flair. ",
                'stock' => 42,
                'imgPath' => 'Products/Racquet/Fierce Team 13 California Pickleball Paddle.png',
                'equipPrice' => 269.00,
            ],
            [
                'productName' => 'LI-NING HYPERPOWER 20',
                'sportCategory' => 'Pickleball',
                'productCategory' => 'Racquet',
                'productBrand' => 'LI- NING',
                'description' => "The LI-NING HYPERPOWER 20 – Black (ACPV019-16) is designed for ultimate power and precision on the court. Featuring a 16mm polymer honeycomb core, it delivers excellent control, reduced vibration, and a solid feel. The carbon fiber face enhances durability and spin, making it perfect for aggressive play. Its ergonomic handle ensures a comfortable grip, while the sleek black design gives it a bold, professional look. Whether you're attacking at the net or controlling rallies, the HYPERPOWER 20 helps you dominate every match.",
                'stock' => 35,
                'imgPath' => 'Products/Racquet/LI-NING HYPERPOWER 20.png',
                'equipPrice' => 299.00,
            ],
            [
                'productName' => 'LI-NING HYPERCONTROL 2',
                'sportCategory' => 'Pickleball',
                'productCategory' => 'Racquet',
                'productBrand' => 'LI- NING',
                'description' => "The LI-NING HYPERCONTROL 2 Pickleball Paddle – Blue/White (ACPV037-10) is built for players who prioritize precision and control. Featuring a polymer honeycomb core, it provides a soft touch, reduced vibrations, and excellent shot consistency. The carbon fiber surface enhances durability and spin, making it ideal for strategic gameplay. Its ergonomic grip ensures comfort and stability during intense rallies, while the sleek blue and white design adds a stylish touch. Whether you're placing accurate dinks or defending powerful shots, the HYPERCONTROL 2 gives you the edge to outplay the competition.",
                'stock' => 32,
                'imgPath' => 'Products/Racquet/LI-NING HYPERCONTROL 2.png',
                'equipPrice' => 279.00,
            ],
            [
                'productName' => 'Clash 100 V3 Tennis Racket',
                'sportCategory' => 'Tennis',
                'productCategory' => 'Racquet',
                'productBrand' => 'WILSON',
                'description' => "The Clash 100 V3 Tennis Racket delivers an exceptional blend of power, control, and flexibility, making it perfect for all-court players. Featuring FORTYFIVE° carbon construction, it enhances stability while maintaining a comfortable, arm-friendly feel. The revised string pattern improves consistency and precision, while the enhanced frame design increases sweet spot responsiveness. With its lightweight maneuverability and balanced performance, the Clash 100 V3 offers explosive shots with superior feel, helping players dominate the game with confidence.",
                'stock' => 22,
                'imgPath' => 'Products/Racquet/Clash 100 V3 Tennis Racket.png',
                'equipPrice' => 1079.00,
            ],
            [
                'productName' => 'Ultra 100L V4 Tennis Racket',
                'sportCategory' => 'Tennis',
                'productCategory' => 'Racquet',
                'productBrand' => 'WILSON',
                'description' => "The Ultra 100L V4 Tennis Racket is designed for players seeking lightweight power, speed, and maneuverability. Featuring an updated FORTYFIVE° carbon construction, it enhances stability and responsiveness while maintaining a comfortable feel. The reengineered beam design increases power and consistency, while the reduced weight (L model) allows for faster swings and better control. With a larger sweet spot and improved stability, the Ultra 100L V4 is perfect for intermediate players looking to generate effortless power and precision on every shot.",
                'stock' => 32,
                'imgPath' => 'Products/Racquet/Ultra 100L V4 Tennis Racket.png',
                'equipPrice' => 879.00,
            ],
            [
                'productName' => 'EZONE 98',
                'sportCategory' => 'Tennis',
                'productCategory' => 'Racquet',
                'productBrand' => 'YONEX',
                'description' => "The EZONE 98 is a powerful and precision-focused tennis racket, ideal for aggressive baseline players. Featuring 2G-Namd Speed technology, it enhances frame flex and energy return for explosive shots. The Isometric head shape expands the sweet spot, providing more forgiveness and consistency. With a midweight 98 sq. inch frame, it delivers a perfect balance of control, spin, and power. The shock-absorbing VDM (Vibration Dampening Mesh) ensures a smoother, more comfortable feel. Whether attacking from the baseline or controlling rallies, the EZONE 98 helps elevate your game to the next level.",
                'stock' => 18,
                'imgPath' => 'Products/Racquet/EZONE_98.png',
                'equipPrice' => 679.00,
            ],
            
            //Shuttlecock
            [
                'productName' => 'YONEX AEROSENSA 50',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Shuttlecock',
                'productBrand' => 'YONEX',
                'description' => "YONEX AEROSENSA shuttlecocks are the official shuttlecock for the world’s leading international",
                'stock' => 150,
                'imgPath' => 'Products/Shuttlecock/YONEX AEROSENSA 50.png',
                'equipPrice' => 126.00,
            ],
            [
                'productName' => 'YONEX MAVIS 2000',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Shuttlecock',
                'productBrand' => 'YONEX',
                'description' => "Designed to be the ultimate practice and tournament shuttlecock for club players",
                'stock' => 30,
                'imgPath' => 'Products/Shuttlecock/YONEX MAVIS 2000.png',
                'equipPrice' => 64.90,
            ],
            [
                'productName' => 'LI- NING C80',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Shuttlecock',
                'productBrand' => 'LI- NING',
                'description' => "Recommended Ball Amateur Competitions, Flight Stabilization, Clear Ball Feel",
                'stock' => 30,
                'imgPath' => 'Products/Shuttlecock/LI- NING C80.png',
                'equipPrice' => 89.00,
            ],
            [
                'productName' => 'LI- NING G600',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Shuttlecock',
                'productBrand' => 'LI- NING',
                'description' => "Professional Choice, Natural Cork Ball Head, Flight Resistance, Precise Direction, Comfortable Feel",
                'stock' => 85,
                'imgPath' => 'Products/Shuttlecock/LI- NING_G600.png',
                'equipPrice' => 119.00,
            ],
            [
                'productName' => 'VICTOR MASTER NO.1',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Shuttlecock',
                'productBrand' => 'VICTOR',
                'description' => "3 Layers Cork Head, Approved by BWF for International Play, Speed 77",
                'stock' => 50,
                'imgPath' => 'Products/Shuttlecock/VICTOR MASTER NO.1.png',
                'equipPrice' => 115.00,
            ],
            [
                'productName' => 'VICTOR GOLD 77 Speed',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Shuttlecock',
                'productBrand' => 'VICTOR',
                'description' => "Composite Cork, Speed 77",
                'stock' => 35,
                'imgPath' => 'Products/Shuttlecock/VICTOR_GOLD_77_Speed.png',
                'equipPrice' => 73.00,
            ],
            //Bags
            [
                'productName' => 'YONEX LIMITED PRO TOURNAMENT BAG',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Bags',
                'productBrand' => 'YONEX',
                'description' => "A stylish and eco-friendly racquet bag available in White, Navy, and Red. Designed for sustainability, it is made with more than 70% recycled polyester. Dimensions: 75 x 20 x 33 cm, offering ample storage for racquets and gear.",
                'stock' => 25,
                'imgPath' => 'Products/Bags/YONEX LIMITED PRO TOURNAMENT BAG.png',
                'equipPrice' => 589.00,
            ],
            [
                'productName' => 'YONEX PRO TROLLEY BAG',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Bags',
                'productBrand' => 'YONEX',
                'description' => "A spacious and durable racquet bag available in White, Navy, and Red. Features a zipper closure for secure storage. Dimensions: 80 x 36 x 34 cm, providing ample space for racquets and other gear.",
                'stock' => 7,
                'imgPath' => 'Products/Bags/YONEX PRO TROLLEY BAG.png',
                'equipPrice' => 779.90,
            ],
            [
                'productName' => 'LI- NING TOURNAMENT- ABJT049-1',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Bags',
                'productBrand' => 'LI- NING',
                'description' => "A premium black racquet bag made from high-quality polyester with vinyl appointments. Features foam-insulated sides for added protection. Designed with two main compartments: one spacious section for 6+ racquets and another for essentials like shuttles, grips, wallets, phones, and more. Built with precision-reinforced stitching for durability and fine attention to detail. Dimensions: 75 x 25 x 34 cm.",
                'stock' => 2,
                'imgPath' => 'Products/Bags/LI- NING TOURNAMENT- ABJT049-1.png',
                'equipPrice' => 699.00,
            ],
            [
                'productName' => 'LI- NING 6-IN-1 RACQUET BAG- ABJT011-2',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Bags',
                'productBrand' => 'LI- NING',
                'description' => "A high-quality racquet bag available in White and Blue, designed for racquet sports enthusiasts. Offers ample space for up to 6 racquets, with dedicated compartments for shoes, water bottles, and personal items. Features a sleek and modern design that combines functionality with style. Dimensions: 72 x 24 x 30 cm.",
                'stock' => 12,
                'imgPath' => 'Products/Bags/LI- NING 6-IN-1 RACQUET BAG- ABJT011-2.png',
                'equipPrice' => 359.00,
            ],
            [
                'productName' => 'VICTOR x CRAYON SHINCHAN BR5601CS-E',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Bags',
                'productBrand' => 'VICTOR',
                'description' => "A versatile yellow racquet bag made from durable polyester. Features a multi-functional front organizer for accessories, a professional independent shoe compartment for convenient and tidy storage, and a dedicated racquet compartment to securely hold and organize gear. Dimensions: 75 x 20 x 32 cm.",
                'stock' => 10,
                'imgPath' => 'Products/Bags/VICTOR x CRAYON SHINCHAN BR5601CS-E.png',
                'equipPrice' => 389.00,
            ],
            [
                'productName' => 'VICTOR BACKPACK BADMINTON BAG BR7007',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Bags',
                'productBrand' => 'VICTOR',
                'description' => "A durable racquet bag available in Black and Blue, made from high-quality polyester for long-lasting use. Spacious design with dimensions 37 x 33 x 74 cm, providing ample storage for racquets and gear.",
                'stock' => 17,
                'imgPath' => 'Products/Bags/VICTOR BACKPACK BADMINTON BAG BR7007.png',
                'equipPrice' => 309.00,
            ],
            [
                'productName' => 'Chris Brickley Evolution Basketball Bag',
                'sportCategory' => 'Basketball',
                'productCategory' => 'Bags',
                'productBrand' => 'WILSON',
                'description' => "The Chris Brickley Evolution Basketball Bag is a premium gear essential for players on the go. Designed in collaboration with elite trainer Chris Brickley, this bag features a spacious main compartment to securely store your basketball and other essentials. Its durable, high-quality material ensures long-lasting use, while the adjustable shoulder straps provide comfortable carrying. With a sleek, stylish design, this bag is perfect for athletes who want both functionality and fashion. Whether heading to practice or the gym, the Chris Brickley Evolution Basketball Bag keeps your gear organized and ready for action. ",
                'stock' => 39,
                'imgPath' => 'Products/Bags/Chris Brickley Evolution Basketball Bag.png',
                'equipPrice' => 405.00,
            ],
            [
                'productName' => 'Evolution Backpack',
                'sportCategory' => 'Basketball',
                'productCategory' => 'Bags',
                'productBrand' => 'WILSON',
                'description' => "The Evolution Backpack is built for athletes who need durability, style, and functionality. Designed with spacious compartments, it easily holds your basketball, gear, and daily essentials. The padded shoulder straps ensure comfort, while the water-resistant material protects your belongings from the elements. Featuring a sleek and modern design, this backpack is perfect for both sports and everyday use. Whether you're heading to the court, gym, or school, the Evolution Backpack keeps your essentials secure and ready for action.",
                'stock' => 27,
                'imgPath' => 'Products/Bags/Evolution Backpack.png',
                'equipPrice' => 245.90,
            ],
            [
                'productName' => 'LI-NING CBA BASKETBALL BACKPACK - ABSR283-1',
                'sportCategory' => 'Basketball',
                'productCategory' => 'Bags',
                'productBrand' => 'LI- NING',
                'description' => "The LI-NING CBA Basketball Backpack (ABSR283-1) is designed for basketball enthusiasts who need both style and functionality. With a spacious main compartment, it easily fits a basketball, shoes, and other essentials. The ergonomic padded shoulder straps provide all-day comfort, while the durable, water-resistant material ensures protection against the elements. Featuring the CBA (Chinese Basketball Association) branding, this backpack showcases a sleek and sporty design, perfect for athletes on the go. Whether you're heading to practice, the gym, or traveling, the LI-NING CBA Basketball Backpack keeps your gear organized and ready for action. ",
                'stock' => 22,
                'imgPath' => 'Products/Bags/LI-NING CBA BASKETBALL BACKPACK - ABSR283-1.png',
                'equipPrice' => 399.00,
            ],
            [
                'productName' => 'Pickleball Backpack',
                'sportCategory' => 'Pickleball',
                'productCategory' => 'Bags',
                'productBrand' => 'WILSON',
                'description' => "The Pickleball Backpack is the perfect companion for players who need style, storage, and convenience on and off the court. Designed with spacious compartments, it securely holds paddles, balls, shoes, and other essentials. The dedicated paddle pocket ensures protection, while the padded shoulder straps provide all-day comfort. Made from durable, water-resistant material, this backpack keeps your gear safe in any weather. Whether you're heading to practice, a tournament, or casual play, the Pickleball Backpack keeps you organized and ready for action.",
                'stock' => 7,
                'imgPath' => 'Products/Bags/Pickleball Backpack.png',
                'equipPrice' => 440.00,
            ],
            [
                'productName' => 'PICKLEBALL LIFESTYLE TOTE BAG',
                'sportCategory' => 'Pickleball',
                'productCategory' => 'Bags',
                'productBrand' => 'WILSON',
                'description' => "The Pickleball Lifestyle Tote Bag blends style and functionality for players on the go. Designed with spacious compartments, it easily holds paddles, balls, water bottles, and daily essentials. Made from durable, lightweight fabric, it offers long-lasting use while remaining comfortable to carry. The sleek and modern design makes it perfect for both on-court and everyday activities. Whether you're heading to a game, gym, or casual outing, the Pickleball Lifestyle Tote Bag is your go-to accessory for convenience and style.",
                'stock' => 17,
                'imgPath' => 'Products/Bags/PICKLEBALL LIFESTYLE TOTE BAG.png',
                'equipPrice' => 312.70,
            ],
            [
                'productName' => 'PRO GOLF BAG',
                'sportCategory' => 'Golf',
                'productCategory' => 'Bags',
                'productBrand' => 'YONEX',
                'description' => "The Pro Golf Bag is designed for golfers who demand premium quality, functionality, and style. Featuring a lightweight yet durable construction, it offers multiple spacious compartments for clubs, balls, apparel, and accessories. The padded shoulder straps and ergonomic design ensure comfortable carrying, while the sturdy stand or cart-compatible base provides stability on any course. With water-resistant materials and extra storage pockets, this bag keeps your gear organized and protected in all conditions. Whether walking or riding, the Pro Golf Bag is the perfect companion for every round. ",
                'stock' => 7,
                'imgPath' => 'Products/Bags/PRO GOLF BAG.png',
                'equipPrice' => 993.00,
            ],
            [
                'productName' => 'STAND BAG',
                'sportCategory' => 'Golf',
                'productCategory' => 'Bags',
                'productBrand' => 'YONEX',
                'description' => "The Stand Bag is a lightweight and versatile choice for golfers who prefer easy mobility on the course. Designed with built-in retractable legs, it provides stable support on any terrain. Featuring multiple storage compartments, it offers ample space for clubs, balls, apparel, and accessories. The padded dual-strap system ensures comfortable carrying, while the durable, water-resistant material protects your gear in all weather conditions. Whether walking the fairways or practicing at the range, the Stand Bag delivers convenience, functionality, and style.",
                'stock' => 5,
                'imgPath' => 'Products/Bags/STAND BAG.png',
                'equipPrice' => 1009.80,
            ],
            [
                'productName' => 'Clash V3 Super Tour Backpack',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Bags',
                'productBrand' => 'WILSON',
                'description' => "The Clash V3 Super Tour Backpack is a sleek, high-performance bag designed for tennis players who need functionality and style on the go. Featuring a dedicated racket compartment, it securely holds up to two rackets with locking zippers for protection. The main storage section offers ample space for gear, while the ventilated pocket keeps shoes and sweaty clothes separate. Padded adjustable shoulder straps ensure all-day comfort, and the durable, water-resistant material protects against the elements. Whether heading to practice or a match, the Clash V3 Super Tour Backpack keeps you organized and ready to play.",
                'stock' => 5,
                'imgPath' => 'Products/Bags/Clash V3 Super Tour Backpack.png',
                'equipPrice' => 889.80,
            ],
            //Footwear
            [
                'productName' => 'YONEX POWER CUSHION ECLIPSION Z WIDE',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Footwear',
                'productBrand' => 'YONEX',
                'description' => "A high-performance sport shoe available in White and Black, crafted with Synthetic Fiber and Synthetic Resin for durability. Features a Rubber Sole for excellent grip. Equipped with advanced technologies like Power Cushion for superior shock absorption, Double Raschel Mesh for breathability, Durable Skin Light for a lightweight feel, Power Graphite Sheet for stability, and Feather Bounce Foam for enhanced responsiveness on the court.",
                'stock' => 23,
                'imgPath' => 'Products/Footwear/YONEX POWER CUSHION ECLIPSION Z WIDE.png',
                'equipPrice' => 519.90,
            ],
            [
                'productName' => 'YONEX POWER CUSHION COMFORT Z',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Footwear',
                'productBrand' => 'YONEX',
                'description' => "A lightweight and high-performance sport shoe in Mint, made with Synthetic Fiber and Synthetic Resin for durability. Features a Rubber Sole for excellent traction. Equipped with Power Cushion for shock absorption, Double Raschel Mesh for breathability, Durable Skin Light for a lightweight feel, Power Graphite Sheet for stability, msLITE X for enhanced agility, and Feather Bounce Foam for superior responsiveness on the court.",
                'stock' => 32,
                'imgPath' => 'Products/Footwear/YONEX POWER CUSHION COMFORT Z.png',
                'equipPrice' => 569.00,
            ],
            [
                'productName' => 'LI- NING SAGA II LITE- AYTT003-3',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Footwear',
                'productBrand' => 'LI- NING',
                'description' => "A stylish and high-performance sport shoe in White and Yellow, made with Synthetic Fiber and Synthetic Resin for durability. Features a Rubber Sole for excellent grip and stability. Designed for modern players, the Li-Ning SAGA II LITE enhances both style and performance, providing a superior on-court experience.",
                'stock' => 6,
                'imgPath' => 'Products/Footwear/LI- NING SAGA II LITE- AYTT003-3.png',
                'equipPrice' => 499.00,
            ],
            [
                'productName' => 'LI- NING THUNDER CLOUD- AYAS028-4',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Footwear',
                'productBrand' => 'LI- NING',
                'description' => "A breathable and comfortable sport shoe in White Congo Red, made with Synthetic Fiber and Synthetic Resin for durability. Features a Rubber Sole for excellent traction. Designed with multiple ventilation holes on the upper for high breathability, ensuring cool and dry feet during intense gameplay.",
                'stock' => 12,
                'imgPath' => 'Products/Footwear/LI- NING THUNDER CLOUD- AYAS028-4.png',
                'equipPrice' => 799.00,
            ],
            [
                'productName' => 'VICTOR P9200 HANG- C',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Footwear',
                'productBrand' => 'VICTOR',
                'description' => "A durable and high-performance sport shoe in White, made with Microfiber PU Leather, V-Tough, and Double Mesh for enhanced durability and breathability. Features VSR Rubber for superior grip and traction. Equipped with Light Shock, Light Resilient EVA, EnergyMax 3.0, TPU, and Carbon Power for excellent cushioning, stability, and energy return. Available in sizes 255mm to 280mm.",
                'stock' => 21,
                'imgPath' => 'Products/Footwear/VICTOR P9200 HANG- C.png',
                'equipPrice' => 619.00,
            ],
            [
                'productName' => 'VICTOR x CRAYON SHINCHAN Sport Shoes A39CS',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Footwear',
                'productBrand' => 'VICTOR',
                'description' => "A lightweight and durable sport shoe in White, made with PU Leather and Double Mesh for breathability and comfort. Features a Rubber Sole for excellent grip. Equipped with EVA, EnergyMax 3.0, and TPU for superior cushioning, stability, and energy return. Available in sizes 220mm to 300mm.",
                'stock' => 8,
                'imgPath' => 'Products/Footwear/VICTOR x CRAYON SHINCHAN Badminton Shoes A39CS.png',
                'equipPrice' => 449.00,
            ],
            [
                'productName' => 'LI-NING WAY OF WADE PROFESSIONAL - ABAS083-12',
                'sportCategory' => 'Basketball',
                'productCategory' => 'Footwear',
                'productBrand' => 'LI- NING',
                'description' => "The LI-NING WAY OF WADE 10 LOW PIXEL PROFESSIONAL BASKETBALL SHOES – STANDARD WHITE (ABAS083-12) deliver elite performance with a futuristic design. Engineered for speed and agility, they feature a lightweight, breathable upper for maximum comfort and support. The full-length BOOM midsole provides explosive energy return, while the carbon fiber plate enhances stability and responsiveness on the court. The sleek white pixel-inspired design adds a modern touch, making them perfect for both performance and style. Elevate your game with the Way of Wade 10 Low pixel and dominate the competition.",
                'stock' => 38,
                'imgPath' => 'Products/Footwear/LI-NING WAY OF WADE PROFESSIONAL - ABAS083-12.png',
                'equipPrice' => 1009.00,
            ],
            [
                'productName' => 'LI-NING YUSHUAI 18 BASKETBALL SHOES - ABAU009-3',
                'sportCategory' => 'Basketball',
                'productCategory' => 'Footwear',
                'productBrand' => 'LI- NING',
                'description' => "The LI-NING MEN'S YUSHUAI 18 BASKETBALL SHOES – STANDARD WHITE/BLACK (ABAU009-3) are designed for next-level performance on the court. Featuring LI-NING BOOM cushioning technology, they provide explosive energy return and superior comfort. The PROBAR LOC stabilizer enhances foot support, while the high-quality upper ensures durability and breathability. With a sleek white and black design, these shoes deliver both style and functionality. Whether you're making quick cuts or driving to the hoop, the YUSHUAI 18 offers the stability, grip, and responsiveness needed to elevate your game.",
                'stock' => 38,
                'imgPath' => 'Products/Footwear/LI-NING YUSHUAI 18 BASKETBALL SHOES - ABAU009-3.png',
                'equipPrice' => 1009.00,
            ],
            //Apparel
            [
                'productName' => 'YONEX MEN’S T-SHIRT 16634EX CLEAR RED',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Apparel',
                'productBrand' => 'YONEX',
                'description' => "A lightweight and durable sport outfit in Red, made from 100% Polyester for breathability and comfort during gameplay.",
                'stock' => 32,
                'imgPath' => 'Products/Apparel/YONEX MEN’S T-SHIRT 16634EX CLEAR RED.png',
                'equipPrice' => 132.90,
            ],
            [
                'productName' => 'YONEX MALAYSIA MASTER 2024 T-SHIRT 2842',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Apparel',
                'productBrand' => 'YONEX',
                'description' => "A lightweight and breathable sport outfit in White, made from 100% Polyester for comfort and durability during gameplay.",
                'stock' => 22,
                'imgPath' => 'Products/Apparel/YONEX MALAYSIA MASTER 2024 T-SHIRT 2842.png',
                'equipPrice' => 64.90,
            ],
            [
                'productName' => 'YONEX MEN’S SLEEVELESS TOP 10497EX',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Apparel',
                'productBrand' => 'YONEX',
                'description' => "A flexible and breathable sport outfit in Blue, made from 88% Polyester and 12% Polyurethane, offering durability, comfort, and enhanced mobility during gameplay",
                'stock' => 30,
                'imgPath' => 'Products/Apparel/YONEX MEN’S SLEEVELESS TOP 10497EX.png',
                'equipPrice' => 229.00,
            ],
            [
                'productName' => 'LI-NING MEN’S COMPETITION- AAYT073-5',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Apparel',
                'productBrand' => 'LI- NING',
                'description' => "A lightweight and breathable sport outfit in Yellow, made from 100% Polyester for comfort and durability during gameplay.",
                'stock' => 5,
                'imgPath' => 'Products/Apparel/LI-NING MEN’S COMPETITION- AAYT073-5.png',
                'equipPrice' => 299.00,
            ],
            [
                'productName' => 'VICTOR T- SHIRT T-40008',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Apparel',
                'productBrand' => 'VICTOR',
                'description' => "A lightweight and breathable sport outfit in Green, made from 100% Polyester for comfort and durability during gameplay.",
                'stock' => 13,
                'imgPath' => 'Products/Apparel/VICTOR T- SHIRT T-40008.png',
                'equipPrice' => 93.00,
            ],
            [
                'productName' => 'VICTOR T- SHIRT T-40012',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Apparel',
                'productBrand' => 'VICTOR',
                'description' => "A lightweight and breathable sport outfit in White, made from 100% Polyester for comfort and durability during gameplay.",
                'stock' => 25,
                'imgPath' => 'Products/Apparel/VICTOR T-SHIRT T-40012.png',
                'equipPrice' => 93.00,
            ],
            //Accessories
            [
                'productName' => 'YONEX CUSHION WRAP',
                'sportCategory' => 'Badminton',
                'productCategory' => 'Accessories',
                'productBrand' => 'YONEX',
                'description' => "Non-slip performance with maximum absorbency",
                'stock' => 20,
                'imgPath' => 'Products/Accessories/YONEX CUSHION WRAP.png',
                'equipPrice' => 31.00,
            ],
            [
                'productName' => 'LI-NING TEAM WRISTBAND-RED-AHWE260-2',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Accessories',
                'productBrand' => 'LI- NING',
                'description' => "The Li-Ning GP24 is an optimal match for your grip requirements as it is ultra-light, durable, and provides extra support to your palms. Its base material is polyurethane, has a tacky texture, and is ideal for those with a dry palm. In addition, this over grip uses the classic anti-slip technology and is designed so that the racket perfectly locks in your hand.",
                'stock' => 10,
                'imgPath' => 'Products/Accessories/LI-NING TEAM WRISTBAND RED.png',
                'equipPrice' => 15.00,
            ],
            [
                'productName' => 'VICTOR Badminton Grip Powder AC018',
                'sportCategory' => 'Multi-Sport',
                'productCategory' => 'Accessories',
                'productBrand' => 'VICTOR',
                'description' => "A high-performance grip powder designed with anti-slip properties to enhance racket handling and control. Made from Polyurethane and EVA, it absorbs moisture and provides a secure grip for improved performance during gameplay.",
                'stock' => 50,
                'imgPath' => 'Products/Accessories/VICTOR Badminton Grip Powder AC018.png',
                'equipPrice' => 21.90,
            ],
            //Balls
            [
                'productName' => '2024 NBA Finals Official Game Basketball',
                'sportCategory' => 'Basketball',
                'productCategory' => 'Balls',
                'productBrand' => 'WILSON',
                'description' => "The 2024 NBA Finals Official Game Basketball is the ultimate choice for basketball enthusiasts and collectors. Made with premium composite leather, it offers exceptional grip, control, and durability. Designed for professional play, it meets official NBA size and weight standards. This limited-edition ball features the official NBA Finals 2024 logo, making it a must-have for fans. Whether for game use or display, it embodies the spirit of championship basketball. Get yours now and own a piece of NBA history! ",
                'stock' => 20,
                'imgPath' => 'Products/Balls/2024 NBA Finals Official Game Basketball.png',
                'equipPrice' => 899.90,
            ],
            [
                'productName' => 'Evolution Game Basketball',
                'sportCategory' => 'Basketball',
                'productCategory' => 'Balls',
                'productBrand' => 'WILSON',
                'description' => "The Evolution Game Basketball is designed for elite performance, offering exceptional grip, soft feel, and superior control. Crafted with high-quality microfiber composite leather, it delivers optimal handling for both indoor and outdoor play. Its cushion core technology ensures a consistent bounce, making it a favorite among competitive players. Whether you're training or competing, the Evolution Game Basketball enhances your game with precision and durability. ",
                'stock' => 7,
                'imgPath' => 'Products/Balls/Evolution Game Basketball.png',
                'equipPrice' => 319.80,
            ],
            [
                'productName' => 'WNBA White & Gold Basketball',
                'sportCategory' => 'Basketball',
                'productCategory' => 'Balls',
                'productBrand' => 'WILSON',
                'description' => "The WNBA White & Gold Basketball is a stunning blend of style and performance, celebrating the excellence of women’s basketball. Featuring a premium composite leather cover, it offers superior grip and control for both indoor and outdoor play. The iconic white and gold design adds a touch of elegance, making it perfect for games, training, or display. Whether you're a dedicated player or a passionate fan, this ball is a must-have to honor the WNBA's legacy. ",
                'stock' => 20,
                'imgPath' => 'Products/Balls/WNBA White & Gold Basketball.png',
                'equipPrice' => 183.80,
            ],
            [
                'productName' => 'LI-NING BASKETBALL NO.5.03 - ABQK118-1',
                'sportCategory' => 'Basketball',
                'productCategory' => 'Balls',
                'productBrand' => 'LI- NING',
                'description' => "The LI-NING BASKETBALL NO.5.03 - ABQK118-1 is built for precision and durability, perfect for both casual and competitive play. Made with high-quality synthetic leather, it provides excellent grip and control on the court. Its advanced design ensures consistent performance, making it ideal for indoor and outdoor games. With vibrant colors and a sleek finish, this ball stands out while delivering superior bounce and responsiveness. Whether you’re practicing your skills or in a game, the LI-NING BASKETBALL NO.5.03 offers top-tier quality and performance.",
                'stock' => 15,
                'imgPath' => 'Products/Balls/LI-NING BASKETBALL NO.5.03 - ABQK118-1.png',
                'equipPrice' => 79.00,
            ],
            [
                'productName' => 'LI-NING BADFIVE ELITE BASKETBALL - ABQT077-3',
                'sportCategory' => 'Basketball',
                'productCategory' => 'Balls',
                'productBrand' => 'LI- NING',
                'description' => "The LI-NING BADFIVE ELITE BASKETBALL - PINK/NAVY (ABQT077-3) combines style and performance for street and indoor courts. Its premium composite leather surface ensures a superior grip, durability, and excellent ball control. Designed for precision play, it features deep channels for improved handling and a cushioned core for a consistent bounce. The bold pink and navy colorway adds a unique, eye-catching touch, making it perfect for players who want to stand out. Whether for training or competition, the BADFIVE ELITE delivers elite performance with urban flair.",
                'stock' => 12,
                'imgPath' => 'Products/Balls/LI-NING BADFIVE ELITE BASKETBALL - ABQT077-3.png',
                'equipPrice' => 169.00,
            ],
            [
                'productName' => 'LI-NING BADFIVE ELITE BASKETBALL - ABQT075-1',
                'sportCategory' => 'Basketball',
                'productCategory' => 'Balls',
                'productBrand' => 'LI- NING',
                'description' => "The LI-NING BADFIVE ELITE BASKETBALL - NAVY BLUE/CINERARY (ABQT075-1) is built for high-performance play with a street-style edge. Crafted from premium composite leather, it offers excellent grip, durability, and control for both indoor and outdoor use. Deep channels enhance handling, while the cushioned core ensures a consistent bounce. The bold navy blue and cinerary color combination gives it a sleek, modern look, making it a standout choice for serious players. Whether you're hitting the court for training or competition, the BADFIVE ELITE delivers elite performance with style. ",
                'stock' => 11,
                'imgPath' => 'Products/Balls/LI-NING BADFIVE ELITE BASKETBALL - ABQT075-1.png',
                'equipPrice' => 199.00,
            ],
            [
                'productName' => 'LI-NING PG40 PICKLEBALL COMPETITION OUTDOOR BALL',
                'sportCategory' => 'Pickleball',
                'productCategory' => 'Balls',
                'productBrand' => 'LI- NING',
                'description' => "The LI-NING PG40 Pickleball Competition Outdoor Ball – Yellow (ACPV001-9) is designed for high-performance play in outdoor conditions. Engineered with durability and precision, it features a seamless, rotationally molded design for a consistent bounce and flight path. The 40-hole aerodynamic pattern ensures optimal airflow, making it stable even in windy conditions. Its high-visibility yellow color enhances tracking, perfect for competitive and recreational play. Whether you're in a tournament or a casual match, the PG40 Outdoor Ball delivers excellent speed, control, and long-lasting durability.",
                'stock' => 11,
                'imgPath' => 'Products/Balls/LI-NING PG40 PICKLEBALL COMPETITION OUTDOOR BALL.png',
                'equipPrice' => 49.00,
            ],
            [
                'productName' => 'LI-NING PZ26 PICKLEBALL TRAINING INDOOR BALL',
                'sportCategory' => 'Pickleball',
                'productCategory' => 'Balls',
                'productBrand' => 'LI- NING',
                'description' => "The LI-NING PZ26 Pickleball Training Indoor Ball (ACPV005-7) is designed for precision and durability during indoor practice sessions. Featuring a 26-hole aerodynamic design, it ensures a smooth, consistent flight and controlled bounce on indoor surfaces. Made from high-quality polymer, it offers excellent durability for extended training use. Its lightweight construction provides a responsive feel, making it perfect for drills and skill development. Whether you're a beginner or an advanced player, the PZ26 Indoor Training Ball helps refine your game with reliable performance.",
                'stock' => 55,
                'imgPath' => 'Products/Balls/LI-NING PZ26 PICKLEBALL TRAINING INDOOR BALL.png',
                'equipPrice' => 29.00,
            ],
            [
                'productName' => 'TRU 32',
                'sportCategory' => 'Pickleball',
                'productCategory' => 'Balls',
                'productBrand' => 'WILSON',
                'description' => "The TRU 32 Ball – 3 Pack is designed for premium pickleball performance with its revolutionary 32-hole pattern, ensuring superior aerodynamics, balance, and consistency. Made with high-quality polymer, these balls offer a durable, responsive bounce for extended play. Engineered for both indoor and outdoor use, the TRU 32 delivers a smooth, true flight with excellent control. Whether you're training or competing, this 3-pack provides reliability and precision for every match.",
                'stock' => 65,
                'imgPath' => 'Products/Balls/TRU_32.png',
                'equipPrice' => 48.00,
            ],
            [
                'productName' => 'WILSON Staff Model X Golf Ball',
                'sportCategory' => 'Golf',
                'productCategory' => 'Balls',
                'productBrand' => 'WILSON',
                'description' => "The WILSON Staff Model X Golf Ball is engineered for elite performance, offering maximum distance, spin, and control. Featuring a 4-piece urethane construction, it delivers exceptional responsiveness and precision on every shot. The high-compression core enhances energy transfer for explosive ball speed, while the advanced aerodynamic design ensures a consistent, penetrating flight. Ideal for players who demand tour-level feel and control, the Staff Model X provides superior greenside spin and workability, making it a top choice for competitive golfers.",
                'stock' => 35,
                'imgPath' => 'Products/Balls/WILSON Staff Model X Golf Ball.png',
                'equipPrice' => 120.00,
            ],
            [
                'productName' => 'WILSON Staff Model Golf Ball',
                'sportCategory' => 'Golf',
                'productCategory' => 'Balls',
                'productBrand' => 'WILSON',
                'description' => "The WILSON Staff Model Golf Ball is designed for tour-level precision, feel, and control. Featuring a 4-piece urethane construction, it provides exceptional spin and responsiveness for both long and short-game performance. The high-compression core ensures maximum energy transfer for explosive distance, while the advanced aerodynamic design promotes a consistent and stable ball flight. Engineered for elite players, the Staff Model Golf Ball delivers superior greenside spin, soft feel, and unmatched shot-shaping capabilities, making it the ultimate choice for serious golfers.",
                'stock' => 15,
                'imgPath' => 'Products/Balls/WILSON_Staff_Model_Golf_Ball.png',
                'equipPrice' => 210.00,
            ],
            [
                'productName' => 'US Open Extra Duty 3 Ball Can',
                'sportCategory' => 'Tennis',
                'productCategory' => 'Balls',
                'productBrand' => 'WILSON',
                'description' => "The US Open Extra Duty 3 Ball Can is the official ball of the US Open, designed for elite performance and durability on hard courts. Featuring extra-duty felt, it withstands the toughest conditions while maintaining consistent bounce and responsiveness. The high-quality rubber core ensures superior playability, while its USTA and ITF approval makes it ideal for competitive matches. Whether for training or tournament play, the US Open Extra Duty Ball delivers exceptional control, speed, and longevity, making it the top choice for serious players.",
                'stock' => 35,
                'imgPath' => 'Products/Balls/US Open Extra Duty 3 Ball Can.png',
                'equipPrice' => 98.00,
            ], 
            [
                'productName' => 'US Open Green Tournament 3 Ball Can',
                'sportCategory' => 'Tennis',
                'productCategory' => 'Balls',
                'productBrand' => 'WILSON',
                'description' => "The US Open Green Tournament 3 Ball Can is designed for junior and developing players transitioning to full-court play. Featuring a slightly lower compression than standard balls, it provides a slower speed and easier control, helping players build confidence and improve technique. The durable felt construction ensures consistent bounce and longevity on all court surfaces. Approved by the USTA and ITF, the US Open Green Tournament Ball is perfect for training, practice, and junior competitions.",
                'stock' => 53,
                'imgPath' => 'Products/Balls/US Open Extra Duty 3 Ball Can.png',
                'equipPrice' => 89.00,
            ], 
            //Clubs
            [
                'productName' => 'EZONE GT DRIVER MAX',
                'sportCategory' => 'Golf',
                'productCategory' => 'Clubs',
                'productBrand' => 'YONEX',
                'description' => "The TRU 32 Ball – 3 Pack is designed for premium pickleball performance with its revolutionary 32-hole pattern, ensuring superior aerodynamics, balance, and consistency. Made with high-quality polymer, these balls offer a durable, responsive bounce for extended play. Engineered for both indoor and outdoor use, the TRU 32 delivers a smooth, true flight with excellent control. Whether you're training or competing, this 3-pack provides reliability and precision for every match.",
                'stock' => 25,
                'imgPath' => 'Products/Clubs/EZONE GT DRIVER MAX.png',
                'equipPrice' => 408.00,
            ],
            [
                'productName' => 'EZONE CB 901 FORGED IRON',
                'sportCategory' => 'Golf',
                'productCategory' => 'Clubs',
                'productBrand' => 'YONEX',
                'description' => "The EZONE CB 901 Forged Iron is designed for golfers seeking precision, feel, and workability. Crafted from premium forged steel, it provides an exceptionally soft yet responsive impact for ultimate shot control. The cavity-back design enhances forgiveness while maintaining a classic player's iron profile. With optimized weight distribution, it delivers consistent ball flight and improved stability on off-center hits. Whether shaping shots or maximizing accuracy, the EZONE CB 901 Forged Iron is the perfect blend of performance and craftsmanship for serious golfers.",
                'stock' => 25,
                'imgPath' => 'Products/Clubs/EZONE CB 901 FORGED IRON.png',
                'equipPrice' => 198.00,
            ],
            [
                'productName' => 'DYNAPWR LS Driver',
                'sportCategory' => 'Golf',
                'productCategory' => 'Clubs',
                'productBrand' => 'WILSON',
                'description' => "The DYNAPWR LS Driver is built for golfers seeking low spin, explosive distance, and precision control. Featuring an advanced carbon composite crown, it optimizes weight distribution for increased clubhead speed and stability. The adjustable weighting system allows fine-tuning of ball flight, while the high-speed face design maximizes energy transfer for powerful drives. Engineered for tour-level performance, the DYNAPWR LS Driver delivers a penetrating trajectory with enhanced workability, making it ideal for skilled players looking to shape their shots with confidence.",
                'stock' => 5,
                'imgPath' => 'Products/Clubs/DYNAPWR LS Driver.png',
                'equipPrice' => 1098.00,
            ],   
        ];

        foreach ($products as $data) {
            $product = Product::updateOrCreate([
                'productName' => $data['productName'],
                'sportCategory' => $data['sportCategory'],
                'productCategory' => $data['productCategory'],
                'productBrand' => $data['productBrand'],
            ]);

            ProductDetail::updateOrCreate([
                'product_id' => $product->id,
                'description' => $data['description'],
                'stock' => $data['stock'],
                'imgPath' => $data['imgPath'],
                'equipPrice' => $data['equipPrice'],
            ]);
        }
    }
}
